export enum CampaignObjective {
    AWARENESS = "AWARENESS",
    ENGAGEMENT = "ENGAGEMENT",
    VIDEO_VIEWS = "VIDEO_VIEWS",
    TRAFFIC = "TRAFFIC",
    LEAD_GENERATION = "LEAD_GENERATION",
    CONVERSIONS = "CONVERSIONS",
    PRODUCT_SALES = "PRODUCT_SALES",
    APP_PROMOTION = "APP_PROMOTION",
    CROSS_OBJECTIVE = "CROSS_OBJECTIVE",
}
